version: "3"
services:
  task1:
    build: ./Task1
    ports:
      - "80:80"
  task2-server:
    container_name: ipc_server_dns_name
    build: ./Task2/server
    networks:
      - my_socket_ipc_network
  task2-client:
    build: ./Task2/client
    networks:
      - my_socket_ipc_network
    depends_on:
      - task2-server
networks:
  my_socket_ipc_network: